export {default as DoughnutChart} from './DoughnutChart/DoughnutChart' 
export {default as Header} from './Header/Header' 
export {default as Footer} from './Footer/Footer' 
export {default as ContactUs} from './ContactUs/ContactUs' 
export {default as Login} from './Login/Login' 
export {default as SignUp} from './SignUp/SignUp' 
export {default as DashboardCard} from './DashboardCard/DashboardCard' 
// export {default as AuthRoute} from './Login/AuthRoute' 
export {default as PageNotFound} from './PageNotFound/PageNotFound' 
export {default as StrokeLine} from './StrokeLine/StrokeLine' 
export {default as StyledButton} from './StyledButton/StyledButton'
export {default as StyledFileInput} from './StyledFileInput/StyledFileInput' 
